name: SBOM Compliance Check

on:
  push:
    paths:
      - '**.spdx.json'
      - '**.json'

jobs:
  compliance-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          sudo apt-get install -y libpango-1.0-0 libgdk-pixbuf2.0-0 libffi-dev  # For WeasyPrint

      - name: Run Compliance Check
        run: python main.py
