# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2025 Your Name <your.email@example.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

name: SBOM Compliance Check

on:
  push:
    paths:
      - '**.spdx.json'
      - '**.json'

jobs:
  compliance-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          sudo apt-get install -y libpango-1.0-0 libgdk-pixbuf2.0-0 libffi-dev  # For WeasyPrint

      - name: Run Compliance Check
        run: python main.py
